"""Core data model for the Beta Magic rules engine."""

from .cards import (
    ActivatedManaAbility,
    ActivatedPumpAbility,
    Card,
    CardDefinition,
    ContinuousEffect,
    CreatureBuff,
    DamageEffect,
    DestroyAllEffect,
    DestroyTargetsEffect,
    EffectRecipient,
    EffectScope,
    MoveTargetsEffect,
    TargetRequirement,
    TemporaryPumpEffect,
    UpkeepDamageEffect,
    UpkeepDamageRecipient,
    UpkeepCostEffect,
    UpkeepFailure,
    VariableCreatureStats,
    VariableStatKind,
)
from .combat_tricks import GIANT_GROWTH, RIGHTEOUSNESS, TARGETED_PUMP_SPELLS
from .dual_lands import (
    BADLANDS,
    BAYOU,
    DUAL_LANDS,
    PLATEAU,
    SAVANNAH,
    SCRUBLAND,
    TAIGA,
    TROPICAL_ISLAND,
    TUNDRA,
    UNDERGROUND_SEA,
    VOLCANIC_ISLAND,
)
from .destruction_spells import (
    ARMAGEDDON,
    DISENCHANT,
    FLASHFIRES,
    ICE_STORM,
    LAND_DESTRUCTION_SPELLS,
    PERMANENT_DESTRUCTION_SPELLS,
    SHATTER,
    SINKHOLE,
    STONE_RAIN,
    TRANQUILITY,
    TSUNAMI,
)
from .damage_spells import LIGHTNING_BOLT, PSIONIC_BLAST, TARGETED_DAMAGE_SPELLS
from .basic_lands import BASIC_LANDS, FOREST, ISLAND, MOUNTAIN, PLAINS, SWAMP
from .enchant_creatures import (
    ABILITY_ENCHANT_CREATURES,
    BLESSING,
    ENCHANT_CREATURES,
    FIREBREATHING,
    FLIGHT,
    BURROWING,
    HOLY_ARMOR,
    HOLY_STRENGTH,
    LANCE,
    PUMP_ENCHANT_CREATURES,
    SIMPLE_ENCHANT_CREATURES,
    UNHOLY_STRENGTH,
    WEAKNESS,
)
from .creature_lords import CREATURE_LORDS, GOBLIN_KING, LORD_OF_ATLANTIS
from .events import (
    CardMovedEvent,
    DamageEvent,
    GameEvent,
    ManaBurnEvent,
    SpellCastEvent,
)
from .game import (
    CombatState,
    GameState,
    PendingCast,
    PendingTimedEvent,
    PlayerState,
)
from .global_enchantments import (
    BAD_MOON,
    CRUSADE,
    GLOBAL_ENCHANTMENTS,
    ORCISH_ORIFLAMME,
)
from .graveyard_spells import (
    GRAVEYARD_RECURSION_SPELLS,
    RAISE_DEAD,
    REGROWTH,
    RESURRECTION,
)
from .flying_creatures import FLYING_CREATURES
from .first_strike_creatures import ELVISH_ARCHERS, FIRST_STRIKE_CREATURES
from .mana import ManaCost, ManaPool
from .landwalk_creatures import BOG_WRAITH, LANDWALK_CREATURES, SHANODIN_DRYADS
from .mana_creatures import BIRDS_OF_PARADISE, LLANOWAR_ELVES, MANA_CREATURES
from .mana_artifacts import (
    BLACK_LOTUS,
    MANA_ARTIFACTS,
    MOX_EMERALD,
    MOX_JET,
    MOX_PEARL,
    MOX_RUBY,
    MOX_SAPPHIRE,
    MOXEN,
    SOL_RING,
)
from .pump_creatures import (
    DRAGON_WHELP,
    FROZEN_SHADE,
    GRANITE_GARGOYLE,
    PUMP_CREATURES,
    SHIVAN_DRAGON,
)
from .types import (
    CardType,
    Color,
    CombatStep,
    GameStatus,
    KeywordAbility,
    TurnPhase,
    Zone,
)
from .trample_creatures import TRAMPLE_CREATURES, WAR_MAMMOTH
from .timed_artifacts import COPPER_TABLET, TIMED_ARTIFACTS
from .timed_enchantments import (
    CURSED_LAND,
    FEEDBACK,
    TIMED_ENCHANTMENTS,
    WANDERLUST,
    WARP_ARTIFACT,
)
from .upkeep_creatures import FORCE_OF_NATURE, PHANTASMAL_FORCES, UPKEEP_CREATURES
from .vanilla_creatures import VANILLA_CREATURES
from .vanilla_walls import VANILLA_WALLS, WALL_OF_ICE, WALL_OF_STONE, WALL_OF_WOOD
from .variable_creatures import (
    KELDON_WARLORD,
    NIGHTMARE,
    PLAGUE_RATS,
    VARIABLE_CREATURES,
)

__all__ = [
    "Card",
    "ActivatedManaAbility",
    "ActivatedPumpAbility",
    "CardDefinition",
    "CreatureBuff",
    "ContinuousEffect",
    "EffectScope",
    "EffectRecipient",
    "DamageEffect",
    "DestroyTargetsEffect",
    "DestroyAllEffect",
    "TargetRequirement",
    "TemporaryPumpEffect",
    "UpkeepDamageEffect",
    "UpkeepDamageRecipient",
    "UpkeepCostEffect",
    "UpkeepFailure",
    "VariableCreatureStats",
    "VariableStatKind",
    "MoveTargetsEffect",
    "CardType",
    "CombatState",
    "CombatStep",
    "Color",
    "GameState",
    "GameStatus",
    "KeywordAbility",
    "ManaPool",
    "LANDWALK_CREATURES",
    "BOG_WRAITH",
    "SHANODIN_DRYADS",
    "ManaCost",
    "MANA_CREATURES",
    "LLANOWAR_ELVES",
    "BIRDS_OF_PARADISE",
    "MANA_ARTIFACTS",
    "MOXEN",
    "MOX_PEARL",
    "MOX_SAPPHIRE",
    "MOX_JET",
    "MOX_RUBY",
    "MOX_EMERALD",
    "SOL_RING",
    "BLACK_LOTUS",
    "PUMP_CREATURES",
    "SHIVAN_DRAGON",
    "FROZEN_SHADE",
    "GRANITE_GARGOYLE",
    "DRAGON_WHELP",
    "PlayerState",
    "PendingCast",
    "PendingTimedEvent",
    "TurnPhase",
    "Zone",
    "BASIC_LANDS",
    "DUAL_LANDS",
    "TUNDRA",
    "UNDERGROUND_SEA",
    "BADLANDS",
    "TAIGA",
    "SAVANNAH",
    "SCRUBLAND",
    "VOLCANIC_ISLAND",
    "BAYOU",
    "PLATEAU",
    "TROPICAL_ISLAND",
    "PLAINS",
    "ISLAND",
    "SWAMP",
    "MOUNTAIN",
    "FOREST",
    "VANILLA_CREATURES",
    "VANILLA_WALLS",
    "WALL_OF_ICE",
    "WALL_OF_STONE",
    "WALL_OF_WOOD",
    "FLYING_CREATURES",
    "FIRST_STRIKE_CREATURES",
    "ELVISH_ARCHERS",
    "TRAMPLE_CREATURES",
    "WAR_MAMMOTH",
    "GLOBAL_ENCHANTMENTS",
    "CRUSADE",
    "BAD_MOON",
    "ORCISH_ORIFLAMME",
    "SIMPLE_ENCHANT_CREATURES",
    "HOLY_STRENGTH",
    "UNHOLY_STRENGTH",
    "WEAKNESS",
    "ABILITY_ENCHANT_CREATURES",
    "PUMP_ENCHANT_CREATURES",
    "ENCHANT_CREATURES",
    "LANCE",
    "FLIGHT",
    "BURROWING",
    "BLESSING",
    "HOLY_ARMOR",
    "FIREBREATHING",
    "CREATURE_LORDS",
    "LORD_OF_ATLANTIS",
    "GOBLIN_KING",
    "GameEvent",
    "CardMovedEvent",
    "SpellCastEvent",
    "DamageEvent",
    "ManaBurnEvent",
    "TARGETED_DAMAGE_SPELLS",
    "LIGHTNING_BOLT",
    "PSIONIC_BLAST",
    "PERMANENT_DESTRUCTION_SPELLS",
    "LAND_DESTRUCTION_SPELLS",
    "DISENCHANT",
    "SHATTER",
    "TRANQUILITY",
    "STONE_RAIN",
    "SINKHOLE",
    "ICE_STORM",
    "ARMAGEDDON",
    "FLASHFIRES",
    "TSUNAMI",
    "TARGETED_PUMP_SPELLS",
    "GIANT_GROWTH",
    "RIGHTEOUSNESS",
    "TIMED_ARTIFACTS",
    "COPPER_TABLET",
    "TIMED_ENCHANTMENTS",
    "CURSED_LAND",
    "FEEDBACK",
    "WANDERLUST",
    "WARP_ARTIFACT",
    "UPKEEP_CREATURES",
    "PHANTASMAL_FORCES",
    "FORCE_OF_NATURE",
    "VARIABLE_CREATURES",
    "KELDON_WARLORD",
    "NIGHTMARE",
    "PLAGUE_RATS",
    "GRAVEYARD_RECURSION_SPELLS",
    "REGROWTH",
    "RAISE_DEAD",
    "RESURRECTION",
]
